controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive:
      type: diff_drive_controller/DiffDriveController

diff_drive:
  ros__parameters:
    left_wheels:  ["front_left_wheel",  "rear_left_wheel"]
    right_wheels: ["front_right_wheel", "rear_right_wheel"]

    wheel_separation: 0.28
    wheel_radius:     0.05
    cmd_vel_timeout:  0.5
    publish_rate:     50
    base_frame_id:    base_link
