controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_base_controller:
  ros__parameters:
    use_stamped_vel: false         # matches /cmd_vel_unstamped
    left_wheel_names: ["rear_left_wheel_joint", "front_left_wheel_joint"]
    right_wheel_names: ["rear_right_wheel_joint", "front_right_wheel_joint"]
    wheel_separation: 0.28         # adjust for your URDF
    wheel_radius: 0.05             # adjust for your URDF
    cmd_vel_timeout: 0.25
    publish_rate: 50.0
    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 2.0
    linear.x.min_velocity: -2.0
    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 2.0
    angular.z.min_velocity: -2.0
