<?xml version="1.0"?>

<robot name="limo_four_diff" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="$(find limo_description)/urdf/limo_xacro.xacro" />

    <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159"/>

    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.13" />
    <xacro:property name="base_y_size" value="0.12" />
    <xacro:property name="base_z_size" value="0.1" />
    <xacro:property name="wheelbase" value="0.2"/>
    <xacro:property name="track" value="0.13"/>
    <xacro:property name="wheel_vertical_offset" value="-0.10" />
    <xacro:property name="base_mass" value="2.1557"/>
    <xacro:property name="wheel_length" value="0.045" />
    <xacro:property name="wheel_radius" value="0.045" />

    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 0.15" rpy="0 0 0"/>
    </joint>

    <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 -0.15" rpy="0 0 1.57" />
            <geometry>
                <mesh filename="file://$(find limo_description)/meshes/limo_base.dae" scale="1 1 1"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
            </geometry>
        </collision>
    </link>

    <link name="inertial_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" />
            <mass value="${base_mass}" />
            <inertia ixx="0.24" ixy="0" ixz="0"
                     iyy="0.96" iyz="0"
                     izz="0.96" />
        </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <!-- Sensors -->
    <xacro:limo_laser parent_prefix="base_link" frame_prefix="laser">
        <origin xyz="0.103 0 -0.034" rpy="0 0 0"/>
    </xacro:limo_laser>

    <xacro:limo_depth_camera parent_prefix="base_link" frame_prefix="depth_camera">
        <origin xyz="0.084 0 0.3" rpy="0 0 0"/>
    </xacro:limo_depth_camera>

    <xacro:limo_imu parent_prefix="base_link" frame_prefix="imu">
        <origin xyz="0.0 0 -0.1" rpy="0 0 0"/>
    </xacro:limo_imu>

    <!-- Wheels (links from macro) -->
    <xacro:limo_wheel parent_prefix="base_link" wheel_prefix="front_left" reflect="1">
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:limo_wheel>

    <xacro:limo_wheel parent_prefix="base_link" wheel_prefix="front_right" reflect="-1">
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="${M_PI} 0 0" />
    </xacro:limo_wheel>

    <xacro:limo_wheel parent_prefix="base_link" wheel_prefix="rear_left" reflect="1">
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:limo_wheel>

    <xacro:limo_wheel parent_prefix="base_link" wheel_prefix="rear_right" reflect="-1">
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="${M_PI} 0 0" />
    </xacro:limo_wheel>

    <!-- Gazebo IMU -->
    <gazebo reference="imu_link">
      <gravity>true</gravity>
      <sensor name="twr_imu" type="imu">
        <always_on>true</always_on>
        <update_rate>100</update_rate>
        <visualize>true</visualize>
        <imu>
          <orientation>
            <x><noise type="gaussian"><mean>0.0</mean><stddev>2e-3</stddev></noise></x>
            <y><noise type="gaussian"><mean>0.0</mean><stddev>2e-3</stddev></noise></y>
            <z><noise type="gaussian"><mean>0.0</mean><stddev>2e-3</stddev></noise></z>
          </orientation>
          <angular_velocity>
            <x><noise type="gaussian"><mean>0.0</mean><stddev>2e-4</stddev></noise></x>
            <y><noise type="gaussian"><mean>0.0</mean><stddev>2e-4</stddev></noise></y>
            <z><noise type="gaussian"><mean>0.0</mean><stddev>2e-4</stddev></noise></z>
          </angular_velocity>
          <linear_acceleration>
            <x><noise type="gaussian"><mean>0.0</mean><stddev>1.7e-2</stddev></noise></x>
            <y><noise type="gaussian"><mean>0.0</mean><stddev>1.7e-2</stddev></noise></y>
            <z><noise type="gaussian"><mean>0.0</mean><stddev>1.7e-2</stddev></noise></z>
          </linear_acceleration>
        </imu>
        <plugin name="gz::sim::systems::Imu" filename="libgz-sim8-imu-system.so">
          <ros>
            <remapping>~/out:=/imu/data</remapping>
          </ros>
        </plugin>
      </sensor>
    </gazebo>

    <!-- Gazebo Laser -->
    <gazebo reference="laser_link">
      <sensor name="laser" type="ray">
        <always_on>true</always_on>
        <visualize>true</visualize>
        <update_rate>10</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>120</samples>
              <resolution>1.0</resolution>
              <min_angle>-3.14159</min_angle>
              <max_angle>3.14159</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.3</min>
            <max>15.0</max>
            <resolution>0.015</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </ray>
        <plugin name="scan" filename="libgz-sim8-ros2-ray-sensor-system.so">
          <ros>
            <remapping>~/out:=scan</remapping>
          </ros>
          <output_type>sensor_msgs/LaserScan</output_type>
          <frame_name>laser_link</frame_name>
        </plugin>
      </sensor>
    </gazebo>

    <!-- Wheel contact properties -->
    <gazebo reference="front_left_wheel_link">
      <mu1>100</mu1><mu2>100</mu2><kp>10000000.0</kp><kd>1.0</kd><minDepth>0.01</minDepth><fdir1>1 0 0</fdir1>
    </gazebo>
    <gazebo reference="front_right_wheel_link">
      <mu1>100</mu1><mu2>100</mu2><kp>10000000.0</kp><kd>1.0</kd><minDepth>0.01</minDepth><fdir1>1 0 0</fdir1>
    </gazebo>
    <gazebo reference="rear_left_wheel_link">
      <mu1>100</mu1><mu2>100</mu2><kp>10000000.0</kp><kd>1.0</kd><minDepth>0.01</minDepth><fdir1>1 0 0</fdir1>
    </gazebo>
    <gazebo reference="rear_right_wheel_link">
      <mu1>100</mu1><mu2>100</mu2><kp>10000000.0</kp><kd>1.0</kd><minDepth>0.01</minDepth><fdir1>1 0 0</fdir1>
    </gazebo>

    <!-- DiffDrive Plugin -->
    <gazebo>
      <plugin name="gz::sim::systems::DiffDrive" filename="libgz-sim8-diff-drive-system.so">
        <update_rate>50</update_rate>

        <!-- Left wheels -->
        <left_joint>front_left_wheel</left_joint>
        <left_joint>rear_left_wheel</left_joint>

        <!-- Right wheels -->
        <right_joint>front_right_wheel</right_joint>
        <right_joint>rear_right_wheel</right_joint>

        <!-- Wheel geometry -->
        <wheel_separation>0.172</wheel_separation>
        <wheel_radius>0.045</wheel_radius>

        <!-- ROS interface -->
        <topic>cmd_vel</topic>
        <odom_topic>odom</odom_topic>

        <!-- Frames -->
        <odom_frame>odom</odom_frame>
        <base_frame>base_footprint</base_frame>
      </plugin>
    </gazebo>
</robot>

